### ISSUE TITLE
#1 - User can view To Do items

### ISSUE THREAD

**Issue by scbowler** [scbowler/final-demo#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view a lit of their to do items.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the home page loads the user will be able to see a list of their to do items.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create initial database
- [x] Update `data.sql` to create a dummy user and some to do items

### ☁️ Server

- [x] Add GET /api/todos - Endpoint to get all of a users to do items
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create Home Component
- [x] Make fetch request in CDM oh Home component to GET /api/todos
- [x] Update state with to do data
- [x] Display todo data in home page

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
